package cortex

import (
	"database/sql"
	"fmt"
	"os"
	"path/filepath"
	"time"

	"gopkg.in/yaml.v3"

	"github.com/Fail-Safe/Noema/internal/config"
	"github.com/Fail-Safe/Noema/internal/db"
	"github.com/Fail-Safe/Noema/internal/trace"
)

// Manifest is the cortex.md file at the root of each Cortex.
type Manifest struct {
	Name    string `yaml:"name"`
	Purpose string `yaml:"purpose,omitempty"`
	Owner   string `yaml:"owner,omitempty"`
	Created string `yaml:"created"`
	Version int    `yaml:"version"`
}

type Cortex struct {
	Name string
	Dir  string
	DB   *db.DB
}

// Create initialises a new Cortex on disk and registers it.
// dir is the parent directory; the cortex is created as dir/<name>/.
func Create(name, dir string) error {
	root := filepath.Join(dir, name)
	for _, sub := range []string{"traces", "archive/traces", "trash/traces", "db"} {
		if err := os.MkdirAll(filepath.Join(root, sub), 0o750); err != nil {
			return fmt.Errorf("creating %s: %w", sub, err)
		}
	}

	manifest := Manifest{
		Name:    name,
		Created: time.Now().UTC().Format("2006-01-02"),
		Version: 1,
	}
	data, err := yaml.Marshal(manifest)
	if err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(root, "cortex.md"), data, 0o640); err != nil {
		return fmt.Errorf("writing cortex.md: %w", err)
	}
	if err := os.WriteFile(filepath.Join(root, "AGENT.md"), []byte(agentMDContent(manifest)), 0o640); err != nil {
		return fmt.Errorf("writing AGENT.md: %w", err)
	}

	// Open (and migrate) the DB to initialise the schema.
	conn, err := db.Open(root)
	if err != nil {
		return fmt.Errorf("initialising database: %w", err)
	}
	return conn.Close()
}

// ReadManifest parses the cortex.md manifest in the given cortex directory.
func ReadManifest(dir string) (Manifest, error) {
	data, err := os.ReadFile(filepath.Join(dir, "cortex.md"))
	if err != nil {
		return Manifest{}, fmt.Errorf("reading cortex.md: %w", err)
	}
	var m Manifest
	if err := yaml.Unmarshal(data, &m); err != nil {
		return Manifest{}, fmt.Errorf("parsing cortex.md: %w", err)
	}
	return m, nil
}

// agentMDContent returns the generated AGENT.md content for the given manifest.
func agentMDContent(m Manifest) string {
	purposeLine := ""
	if m.Purpose != "" {
		purposeLine = "- **Purpose:** " + m.Purpose + "\n"
	}
	ownerLine := ""
	if m.Owner != "" {
		ownerLine = "- **Owner:** " + m.Owner + "\n"
	}
	return `# Noema Cortex — Agent Guide

This file was generated by ` + "`noema init`" + `. It describes how to work with
this Cortex as an AI agent, with or without the ` + "`noema`" + ` binary or MCP server.

## This Cortex

- **Name:** ` + m.Name + `
` + purposeLine + ownerLine + `- **Created:** ` + m.Created + `

## Concepts

**Cortex** — a named collection of Traces. This directory is a Cortex.

**Trace** — a single memory unit: one markdown file with YAML frontmatter.
The markdown files are the **source of truth**. The SQLite database
(` + "`db/noema.db`" + `) is a derived index and can be rebuilt from the files at
any time with ` + "`noema sync`" + `.

## Directory Layout

` + "```" + `
` + m.Name + `/
  AGENT.md              ← this file
  cortex.md             ← cortex manifest
  traces/               ← active traces
  archive/
    traces/             ← archived (still relevant, lower priority)
  trash/
    traces/             ← soft-deleted, auto-purged after 30 days
  db/
    noema.db            ← SQLite index (do not edit directly)
` + "```" + `

## Trace File Format

Every Trace is a markdown file with YAML frontmatter:

` + "```markdown" + `
---
id: 20260329-why-we-chose-go
title: Why we chose Go
type: decision
author: research-agent-1
tags: [go, language, architecture]
created: 2026-03-29T14:23:00Z
updated: 2026-03-29T14:23:00Z
---

Body content here. Plain markdown, any length.
` + "```" + `

### Frontmatter Fields

| Field | Required | Description |
|---|---|---|
| ` + "`id`" + ` | yes | Matches the filename: ` + "`YYYYMMDD-slugified-title`" + ` |
| ` + "`title`" + ` | yes | Short, descriptive title |
| ` + "`type`" + ` | yes | One of the types listed below |
| ` + "`created`" + ` | yes | RFC3339 UTC timestamp |
| ` + "`updated`" + ` | yes | RFC3339 UTC timestamp — update on every edit |
| ` + "`author`" + ` | no | Human username or agent name |
| ` + "`tags`" + ` | no | YAML list of strings |

## Trace Types

Choose the type that best reflects the **intent** of the memory:

| Type | When to use |
|---|---|
| ` + "`fact`" + ` | A discrete thing that is true |
| ` + "`decision`" + ` | A choice made and why |
| ` + "`preference`" + ` | A behavioral or stylistic lean |
| ` + "`context`" + ` | Situational background |
| ` + "`skill`" + ` | A learned capability or procedure |
| ` + "`intent`" + ` | Something that needs to happen (autonomous pickup) |
| ` + "`observation`" + ` | Something witnessed but not yet verified |
| ` + "`note`" + ` | Anything else |

## Creating a Trace (filesystem)

1. Pick a type and write your content.
2. Generate an ID: today's date + slugified title, e.g. ` + "`20260330-decision-to-use-sqlite`" + `.
3. Write the file to ` + "`traces/<id>.md`" + ` with the frontmatter shown above.
4. Run ` + "`noema sync`" + ` (if available) to update the database index.

## Editing a Trace (filesystem)

Edit the markdown file directly. Always update the ` + "`updated`" + ` timestamp.
Run ` + "`noema sync`" + ` to re-index.

## Archiving / Restoring (filesystem)

- Archive: move the file from ` + "`traces/`" + ` to ` + "`archive/traces/`" + `.
- Restore: move it back to ` + "`traces/`" + `.
- Run ` + "`noema sync`" + ` after either operation.

## Database Sync

If you create, edit, or move trace files directly on the filesystem,
the SQLite index will be out of date until you run:

` + "```" + `
noema sync
` + "```" + `

Sync walks all three trace directories, upserts every file it finds into the
database, and reports how many entries were added, updated, or are orphaned
(in the database but missing on disk).

## MCP Tools (if available)

If a ` + "`noema`" + ` MCP server is connected, prefer the tools over direct file access —
they keep the database in sync automatically:

| Tool | Purpose |
|---|---|
| ` + "`list_traces`" + ` | List traces with optional type/author/tag filters |
| ` + "`get_trace`" + ` | Fetch full content of a trace by ID |
| ` + "`create_trace`" + ` | Create a new trace |
| ` + "`update_trace`" + ` | Update fields of an existing trace |
| ` + "`search_traces`" + ` | Full-text search across titles and bodies |
| ` + "`archive_trace`" + ` | Archive a trace |
| ` + "`unarchive_trace`" + ` | Restore an archived trace |
| ` + "`delete_trace`" + ` | Move a trace to trash (soft-delete, recoverable) |
| ` + "`recover_trace`" + ` | Restore a trashed trace to active |
`
}

// Open opens an existing Cortex by directory path.
// It ensures required subdirectories exist and auto-purges expired trash.
func Open(name, dir string) (*Cortex, error) {
	for _, sub := range []string{"traces", "archive/traces", "trash/traces"} {
		if err := os.MkdirAll(filepath.Join(dir, sub), 0o750); err != nil {
			return nil, fmt.Errorf("ensuring %s: %w", sub, err)
		}
	}
	conn, err := db.Open(dir)
	if err != nil {
		return nil, err
	}
	cx := &Cortex{Name: name, Dir: dir, DB: conn}

	// Auto-purge expired trash. Best-effort: errors are silently ignored.
	cfg, _ := config.Load()
	days := 30
	if cfg != nil && cfg.TrashDays > 0 {
		days = cfg.TrashDays
	}
	_ = cx.Purge(days)

	// Write AGENT.md if it doesn't exist (e.g. cortex created before this feature).
	agentMDPath := filepath.Join(dir, "AGENT.md")
	if _, err := os.Stat(agentMDPath); os.IsNotExist(err) {
		if m, err := ReadManifest(dir); err == nil {
			_ = os.WriteFile(agentMDPath, []byte(agentMDContent(m)), 0o640)
		}
	}

	return cx, nil
}

func (c *Cortex) Close() error {
	return c.DB.Close()
}

func (c *Cortex) TracesDir() string {
	return filepath.Join(c.Dir, "traces")
}

func (c *Cortex) ArchiveDir() string {
	return filepath.Join(c.Dir, "archive", "traces")
}

func (c *Cortex) TrashDir() string {
	return filepath.Join(c.Dir, "trash", "traces")
}

// TraceFile returns the absolute path to a trace's markdown file.
func (c *Cortex) TraceFile(id string, archived bool) string {
	if archived {
		return filepath.Join(c.ArchiveDir(), id+".md")
	}
	return filepath.Join(c.TracesDir(), id+".md")
}

// TrashFile returns the path for a trace in the trash.
func (c *Cortex) TrashFile(id string) string {
	return filepath.Join(c.TrashDir(), id+".md")
}

// filePath resolves the correct on-disk path for any row state.
func (c *Cortex) filePath(r *Row) string {
	if r.TrashedAt != "" {
		return c.TrashFile(r.ID)
	}
	return c.TraceFile(r.ID, r.ArchivedAt != "")
}

// Add writes a new Trace to disk and inserts it into the DB.
func (c *Cortex) Add(t *trace.Trace) error {
	path := c.TraceFile(t.ID, false)
	if err := t.Write(path); err != nil {
		return fmt.Errorf("writing trace file: %w", err)
	}
	if err := c.insertDB(t); err != nil {
		os.Remove(path)
		return fmt.Errorf("inserting into database: %w", err)
	}
	return nil
}

func (c *Cortex) insertDB(t *trace.Trace) error {
	tx, err := c.DB.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.Exec(
		`INSERT INTO traces (id, title, type, author, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?)`,
		t.ID, t.Title, t.Type, t.Author, t.Created, t.Updated,
	)
	if err != nil {
		return err
	}
	for _, tag := range t.Tags {
		if _, err := tx.Exec(`INSERT INTO trace_tags (trace_id, tag) VALUES (?, ?)`, t.ID, tag); err != nil {
			return err
		}
	}
	_, err = tx.Exec(`INSERT INTO traces_fts (id, title, body) VALUES (?, ?, ?)`, t.ID, t.Title, t.Body)
	if err != nil {
		return err
	}
	return tx.Commit()
}

// Row is a DB row joined with tags, returned by list/search operations.
type Row struct {
	ID         string
	Title      string
	Type       string
	Author     string
	Tags       []string
	ArchivedAt string
	TrashedAt  string
	CreatedAt  string
	UpdatedAt  string
}

type ListOptions struct {
	Type     string
	Author   string
	Tag      string
	Archived bool // only archived (excludes trashed)
	Trashed  bool // only trashed
	All      bool // active + archived (excludes trashed)
}

func (c *Cortex) List(opts ListOptions) ([]Row, error) {
	q := `SELECT id, title, type, author, archived_at, trashed_at, created_at, updated_at FROM traces WHERE 1=1`
	var args []any

	switch {
	case opts.Trashed:
		q += ` AND trashed_at IS NOT NULL`
	case opts.All:
		q += ` AND trashed_at IS NULL`
	case opts.Archived:
		q += ` AND archived_at IS NOT NULL AND trashed_at IS NULL`
	default:
		q += ` AND archived_at IS NULL AND trashed_at IS NULL`
	}
	if opts.Type != "" {
		q += ` AND type = ?`
		args = append(args, opts.Type)
	}
	if opts.Author != "" {
		q += ` AND author = ?`
		args = append(args, opts.Author)
	}
	if opts.Tag != "" {
		q += ` AND id IN (SELECT trace_id FROM trace_tags WHERE tag = ?)`
		args = append(args, opts.Tag)
	}
	q += ` ORDER BY created_at DESC, rowid DESC`

	rows, err := c.DB.Query(q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return c.scanRows(rows)
}

func (c *Cortex) Search(query string, opts ListOptions) ([]Row, error) {
	q := `
		SELECT t.id, t.title, t.type, t.author, t.archived_at, t.trashed_at, t.created_at, t.updated_at
		FROM traces t
		WHERE t.id IN (SELECT id FROM traces_fts WHERE traces_fts MATCH ?)`
	args := []any{query}

	switch {
	case opts.Trashed:
		q += ` AND t.trashed_at IS NOT NULL`
	case opts.All:
		q += ` AND t.trashed_at IS NULL`
	case opts.Archived:
		q += ` AND t.archived_at IS NOT NULL AND t.trashed_at IS NULL`
	default:
		q += ` AND t.archived_at IS NULL AND t.trashed_at IS NULL`
	}
	if opts.Type != "" {
		q += ` AND t.type = ?`
		args = append(args, opts.Type)
	}
	if opts.Author != "" {
		q += ` AND t.author = ?`
		args = append(args, opts.Author)
	}
	if opts.Tag != "" {
		q += ` AND t.id IN (SELECT trace_id FROM trace_tags WHERE tag = ?)`
		args = append(args, opts.Tag)
	}
	q += ` ORDER BY t.created_at DESC`

	rows, err := c.DB.Query(q, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	return c.scanRows(rows)
}

func (c *Cortex) Get(id string) (*Row, error) {
	var r Row
	var archivedAt, trashedAt *string
	err := c.DB.QueryRow(
		`SELECT id, title, type, author, archived_at, trashed_at, created_at, updated_at FROM traces WHERE id = ?`, id,
	).Scan(&r.ID, &r.Title, &r.Type, &r.Author, &archivedAt, &trashedAt, &r.CreatedAt, &r.UpdatedAt)
	if err != nil {
		return nil, err
	}
	if archivedAt != nil {
		r.ArchivedAt = *archivedAt
	}
	if trashedAt != nil {
		r.TrashedAt = *trashedAt
	}
	r.Tags, err = c.tagsFor(id)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// Remove permanently deletes a trace from disk and the database.
// Use Trash for recoverable deletion.
func (c *Cortex) Remove(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	if err := os.Remove(c.filePath(r)); err != nil && !os.IsNotExist(err) {
		return fmt.Errorf("removing file: %w", err)
	}
	_, err = c.DB.Exec(`DELETE FROM traces WHERE id = ?`, id)
	return err
}

// Trash moves a trace to the trash directory for deferred deletion.
func (c *Cortex) Trash(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	if r.TrashedAt != "" {
		return fmt.Errorf("trace %s is already in trash", id)
	}
	src := c.filePath(r)
	dst := c.TrashFile(id)
	if err := os.Rename(src, dst); err != nil {
		return fmt.Errorf("moving file to trash: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339)
	_, err = c.DB.Exec(`UPDATE traces SET trashed_at = ?, archived_at = NULL WHERE id = ?`, now, id)
	return err
}

// Recover moves a trace out of the trash and back to the active traces directory.
func (c *Cortex) Recover(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	if r.TrashedAt == "" {
		return fmt.Errorf("trace %s is not in trash", id)
	}
	src := c.TrashFile(id)
	dst := c.TraceFile(id, false)
	if err := os.Rename(src, dst); err != nil {
		return fmt.Errorf("recovering file from trash: %w", err)
	}
	_, err = c.DB.Exec(`UPDATE traces SET trashed_at = NULL WHERE id = ?`, id)
	return err
}

// Purge permanently deletes traces that have been in the trash for more than
// days days. A days value of 0 is treated as 30.
func (c *Cortex) Purge(days int) error {
	if days <= 0 {
		days = 30
	}
	cutoff := time.Now().UTC().Add(-time.Duration(days) * 24 * time.Hour).Format(time.RFC3339)
	rows, err := c.DB.Query(`SELECT id FROM traces WHERE trashed_at IS NOT NULL AND trashed_at < ?`, cutoff)
	if err != nil {
		return err
	}
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			rows.Close()
			return err
		}
		ids = append(ids, id)
	}
	rows.Close()
	if err := rows.Err(); err != nil {
		return err
	}
	for _, id := range ids {
		if err := os.Remove(c.TrashFile(id)); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("purging %s: %w", id, err)
		}
		if _, err := c.DB.Exec(`DELETE FROM traces WHERE id = ?`, id); err != nil {
			return fmt.Errorf("purging %s from db: %w", id, err)
		}
	}
	return nil
}

func (c *Cortex) Archive(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	if r.TrashedAt != "" {
		return fmt.Errorf("trace %s is in trash — recover it first", id)
	}
	if r.ArchivedAt != "" {
		return fmt.Errorf("trace %s is already archived", id)
	}
	src := c.TraceFile(id, false)
	dst := c.TraceFile(id, true)
	if err := os.Rename(src, dst); err != nil {
		return fmt.Errorf("moving file: %w", err)
	}
	now := time.Now().UTC().Format(time.RFC3339)
	_, err = c.DB.Exec(`UPDATE traces SET archived_at = ? WHERE id = ?`, now, id)
	return err
}

func (c *Cortex) Unarchive(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	if r.ArchivedAt == "" {
		return fmt.Errorf("trace %s is not archived", id)
	}
	src := c.TraceFile(id, true)
	dst := c.TraceFile(id, false)
	if err := os.Rename(src, dst); err != nil {
		return fmt.Errorf("moving file: %w", err)
	}
	_, err = c.DB.Exec(`UPDATE traces SET archived_at = NULL WHERE id = ?`, id)
	return err
}

// Update rewrites an existing trace's DB row and FTS entry from its (potentially
// edited) markdown file on disk.
func (c *Cortex) Update(id string) error {
	r, err := c.Get(id)
	if err != nil {
		return err
	}
	t, err := trace.ParseFile(c.filePath(r))
	if err != nil {
		return err
	}
	tx, err := c.DB.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	_, err = tx.Exec(
		`UPDATE traces SET title=?, type=?, author=?, updated_at=? WHERE id=?`,
		t.Title, t.Type, t.Author, t.Updated, id,
	)
	if err != nil {
		return err
	}
	if _, err := tx.Exec(`DELETE FROM trace_tags WHERE trace_id = ?`, id); err != nil {
		return err
	}
	for _, tag := range t.Tags {
		if _, err := tx.Exec(`INSERT INTO trace_tags (trace_id, tag) VALUES (?, ?)`, id, tag); err != nil {
			return err
		}
	}
	if _, err := tx.Exec(`DELETE FROM traces_fts WHERE id = ?`, id); err != nil {
		return err
	}
	if _, err := tx.Exec(`INSERT INTO traces_fts (id, title, body) VALUES (?, ?, ?)`, id, t.Title, t.Body); err != nil {
		return err
	}
	return tx.Commit()
}

func (c *Cortex) scanRows(rows *sql.Rows) ([]Row, error) { //nolint:govet
	var result []Row
	for rows.Next() {
		var r Row
		var archivedAt, trashedAt *string
		if err := rows.Scan(&r.ID, &r.Title, &r.Type, &r.Author, &archivedAt, &trashedAt, &r.CreatedAt, &r.UpdatedAt); err != nil {
			return nil, err
		}
		if archivedAt != nil {
			r.ArchivedAt = *archivedAt
		}
		if trashedAt != nil {
			r.TrashedAt = *trashedAt
		}
		tags, err := c.tagsFor(r.ID)
		if err != nil {
			return nil, err
		}
		r.Tags = tags
		result = append(result, r)
	}
	return result, rows.Err()
}

// SyncResult summarises what Sync found.
type SyncResult struct {
	Added    int // files found on disk but not in DB
	Updated  int // files found on disk and already in DB (re-synced)
	Orphaned int // IDs in DB with no corresponding file on disk
}

// Sync reconciles the database with the current state of the markdown files on
// disk. It walks traces/, archive/traces/, and trash/traces/, upserts every
// file it finds, and reports orphaned DB rows (not deleted — just reported).
func (c *Cortex) Sync() (SyncResult, error) {
	type entry struct {
		path  string
		state string // "active" | "archived" | "trashed"
	}

	var entries []entry
	walkDir := func(dir, state string) error {
		files, err := os.ReadDir(dir)
		if os.IsNotExist(err) {
			return nil
		}
		if err != nil {
			return err
		}
		for _, f := range files {
			if !f.IsDir() && filepath.Ext(f.Name()) == ".md" {
				entries = append(entries, entry{filepath.Join(dir, f.Name()), state})
			}
		}
		return nil
	}
	if err := walkDir(c.TracesDir(), "active"); err != nil {
		return SyncResult{}, err
	}
	if err := walkDir(c.ArchiveDir(), "archived"); err != nil {
		return SyncResult{}, err
	}
	if err := walkDir(c.TrashDir(), "trashed"); err != nil {
		return SyncResult{}, err
	}

	seenIDs := make(map[string]bool)
	now := time.Now().UTC().Format(time.RFC3339)
	var result SyncResult

	for _, e := range entries {
		t, err := trace.ParseFile(e.path)
		if err != nil {
			continue // skip malformed files
		}
		seenIDs[t.ID] = true

		existing, dbErr := c.Get(t.ID)

		// Determine what archived_at and trashed_at should be.
		var archivedAt, trashedAt *string
		switch e.state {
		case "archived":
			if dbErr == nil && existing.ArchivedAt != "" {
				archivedAt = &existing.ArchivedAt // preserve original timestamp
			} else {
				archivedAt = &now
			}
		case "trashed":
			if dbErr == nil && existing.TrashedAt != "" {
				trashedAt = &existing.TrashedAt
			} else {
				trashedAt = &now
			}
		}

		tx, err := c.DB.Begin()
		if err != nil {
			return result, err
		}

		if dbErr != nil {
			// Not in DB — insert.
			_, err = tx.Exec(
				`INSERT INTO traces (id, title, type, author, created_at, updated_at, archived_at, trashed_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
				t.ID, t.Title, t.Type, t.Author, t.Created, t.Updated, archivedAt, trashedAt,
			)
			if err != nil {
				tx.Rollback()
				return result, fmt.Errorf("inserting %s: %w", t.ID, err)
			}
			result.Added++
		} else {
			// Already in DB — update metadata and reconcile state.
			_, err = tx.Exec(
				`UPDATE traces SET title=?, type=?, author=?, updated_at=?, archived_at=?, trashed_at=? WHERE id=?`,
				t.Title, t.Type, t.Author, t.Updated, archivedAt, trashedAt, t.ID,
			)
			if err != nil {
				tx.Rollback()
				return result, fmt.Errorf("updating %s: %w", t.ID, err)
			}
			result.Updated++
		}

		if _, err := tx.Exec(`DELETE FROM trace_tags WHERE trace_id = ?`, t.ID); err != nil {
			tx.Rollback()
			return result, err
		}
		for _, tag := range t.Tags {
			if _, err := tx.Exec(`INSERT INTO trace_tags (trace_id, tag) VALUES (?, ?)`, t.ID, tag); err != nil {
				tx.Rollback()
				return result, err
			}
		}
		if _, err := tx.Exec(`DELETE FROM traces_fts WHERE id = ?`, t.ID); err != nil {
			tx.Rollback()
			return result, err
		}
		if _, err := tx.Exec(`INSERT INTO traces_fts (id, title, body) VALUES (?, ?, ?)`, t.ID, t.Title, t.Body); err != nil {
			tx.Rollback()
			return result, err
		}
		if err := tx.Commit(); err != nil {
			return result, err
		}
	}

	// Count orphaned DB rows.
	rows, err := c.DB.Query(`SELECT id FROM traces`)
	if err != nil {
		return result, err
	}
	defer rows.Close()
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return result, err
		}
		if !seenIDs[id] {
			result.Orphaned++
		}
	}
	return result, rows.Err()
}

func (c *Cortex) tagsFor(id string) ([]string, error) {
	rows, err := c.DB.Query(`SELECT tag FROM trace_tags WHERE trace_id = ? ORDER BY tag`, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tags []string
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		tags = append(tags, tag)
	}
	return tags, rows.Err()
}

